# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Course.create(course_level: 'Year 1', course_language: 'En', course_title: 'App Development', course_number: 'A', course_image_url: 'https://cdn.pixabay.com/photo/2015/05/28/14/53/ux-788002__480.jpg', course_description: 'This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python. The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”. Once a student completes this course, they will be ready to take more advanced programming courses. This course covers Python 3.')
Course.create(course_level: 'Year 1', course_language: 'En', course_title: 'HTML development', course_number: 'B', course_image_url: 'https://cdn.pixabay.com/photo/2016/02/19/11/19/computer-1209641__480.jpg', course_description: 'This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python. The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”. Once a student completes this course, they will be ready to take more advanced programming courses. This course covers Python 3.')
Course.create(course_level: 'Year 1', course_language: 'En', course_title: 'Networking', course_number: 'C', course_image_url: 'https://cdn.pixabay.com/photo/2020/05/07/03/53/digitization-5140055__480.jpg', course_description: 'This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python. The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”. Once a student completes this course, they will be ready to take more advanced programming courses. This course covers Python 3.')
Course.create(course_level: 'Year 1', course_language: 'En', course_title: 'App Development 02', course_number: 'D', course_image_url: 'https://cdn.pixabay.com/photo/2015/05/28/14/53/ux-788002__480.jpg', course_description: 'This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python. The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”. Once a student completes this course, they will be ready to take more advanced programming courses. This course covers Python 3.')
